# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /org/centers/cvc/software/share/usr.linux.x86_64/bin/cmake

# The command to remove a file.
RM = /org/centers/cvc/software/share/usr.linux.x86_64/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /org/centers/cvc/software/share/usr.linux.x86_64/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /h1/mmatos/F2Dock-refactored_02

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /h1/mmatos/F2Dock-refactored_02

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/org/centers/cvc/software/share/usr.linux.x86_64/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/org/centers/cvc/software/share/usr.linux.x86_64/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /h1/mmatos/F2Dock-refactored_02/CMakeFiles /h1/mmatos/F2Dock-refactored_02/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /h1/mmatos/F2Dock-refactored_02/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fft-utils

# Build rule for target.
fft-utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fft-utils
.PHONY : fft-utils

# fast build rule for target.
fft-utils/fast:
	$(MAKE) -f src/fft-utils/CMakeFiles/fft-utils.dir/build.make src/fft-utils/CMakeFiles/fft-utils.dir/build
.PHONY : fft-utils/fast

#=============================================================================
# Target rules for targets named math

# Build rule for target.
math: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 math
.PHONY : math

# fast build rule for target.
math/fast:
	$(MAKE) -f src/math/CMakeFiles/math.dir/build.make src/math/CMakeFiles/math.dir/build
.PHONY : math/fast

#=============================================================================
# Target rules for targets named misc-ident

# Build rule for target.
misc-ident: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 misc-ident
.PHONY : misc-ident

# fast build rule for target.
misc-ident/fast:
	$(MAKE) -f src/misc-ident/CMakeFiles/misc-ident.dir/build.make src/misc-ident/CMakeFiles/misc-ident.dir/build
.PHONY : misc-ident/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f src/utils/CMakeFiles/utils.dir/build.make src/utils/CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named vol

# Build rule for target.
vol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vol
.PHONY : vol

# fast build rule for target.
vol/fast:
	$(MAKE) -f src/vol/CMakeFiles/vol.dir/build.make src/vol/CMakeFiles/vol.dir/build
.PHONY : vol/fast

#=============================================================================
# Target rules for targets named fast-clash

# Build rule for target.
fast-clash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fast-clash
.PHONY : fast-clash

# fast build rule for target.
fast-clash/fast:
	$(MAKE) -f src/fast-clash/CMakeFiles/fast-clash.dir/build.make src/fast-clash/CMakeFiles/fast-clash.dir/build
.PHONY : fast-clash/fast

#=============================================================================
# Target rules for targets named fast-GB

# Build rule for target.
fast-GB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fast-GB
.PHONY : fast-GB

# fast build rule for target.
fast-GB/fast:
	$(MAKE) -f src/fast-GB/CMakeFiles/fast-GB.dir/build.make src/fast-GB/CMakeFiles/fast-GB.dir/build
.PHONY : fast-GB/fast

#=============================================================================
# Target rules for targets named fast-hydro

# Build rule for target.
fast-hydro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fast-hydro
.PHONY : fast-hydro

# fast build rule for target.
fast-hydro/fast:
	$(MAKE) -f src/fast-hydro/CMakeFiles/fast-hydro.dir/build.make src/fast-hydro/CMakeFiles/fast-hydro.dir/build
.PHONY : fast-hydro/fast

#=============================================================================
# Target rules for targets named fast-LJ

# Build rule for target.
fast-LJ: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fast-LJ
.PHONY : fast-LJ

# fast build rule for target.
fast-LJ/fast:
	$(MAKE) -f src/fast-LJ/CMakeFiles/fast-LJ.dir/build.make src/fast-LJ/CMakeFiles/fast-LJ.dir/build
.PHONY : fast-LJ/fast

#=============================================================================
# Target rules for targets named fast-PQ

# Build rule for target.
fast-PQ: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fast-PQ
.PHONY : fast-PQ

# fast build rule for target.
fast-PQ/fast:
	$(MAKE) -f src/fast-PQ/CMakeFiles/fast-PQ.dir/build.make src/fast-PQ/CMakeFiles/fast-PQ.dir/build
.PHONY : fast-PQ/fast

#=============================================================================
# Target rules for targets named fast-resCont

# Build rule for target.
fast-resCont: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fast-resCont
.PHONY : fast-resCont

# fast build rule for target.
fast-resCont/fast:
	$(MAKE) -f src/fast-resCont/CMakeFiles/fast-resCont.dir/build.make src/fast-resCont/CMakeFiles/fast-resCont.dir/build
.PHONY : fast-resCont/fast

#=============================================================================
# Target rules for targets named PG-range

# Build rule for target.
PG-range: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PG-range
.PHONY : PG-range

# fast build rule for target.
PG-range/fast:
	$(MAKE) -f src/PG-range/CMakeFiles/PG-range.dir/build.make src/PG-range/CMakeFiles/PG-range.dir/build
.PHONY : PG-range/fast

#=============================================================================
# Target rules for targets named F2Dock

# Build rule for target.
F2Dock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 F2Dock
.PHONY : F2Dock

# fast build rule for target.
F2Dock/fast:
	$(MAKE) -f src/f2dock/CMakeFiles/F2Dock.dir/build.make src/f2dock/CMakeFiles/F2Dock.dir/build
.PHONY : F2Dock/fast

#=============================================================================
# Target rules for targets named GB-Rerank

# Build rule for target.
GB-Rerank: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GB-Rerank
.PHONY : GB-Rerank

# fast build rule for target.
GB-Rerank/fast:
	$(MAKE) -f src/GB-rerank/CMakeFiles/GB-Rerank.dir/build.make src/GB-rerank/CMakeFiles/GB-Rerank.dir/build
.PHONY : GB-Rerank/fast

#=============================================================================
# Target rules for targets named XmlRPC

# Build rule for target.
XmlRPC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 XmlRPC
.PHONY : XmlRPC

# fast build rule for target.
XmlRPC/fast:
	$(MAKE) -f src/XmlRPC/CMakeFiles/XmlRPC.dir/build.make src/XmlRPC/CMakeFiles/XmlRPC.dir/build
.PHONY : XmlRPC/fast

#=============================================================================
# Target rules for targets named F2DockServer

# Build rule for target.
F2DockServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 F2DockServer
.PHONY : F2DockServer

# fast build rule for target.
F2DockServer/fast:
	$(MAKE) -f src/F2DockServer/CMakeFiles/F2DockServer.dir/build.make src/F2DockServer/CMakeFiles/F2DockServer.dir/build
.PHONY : F2DockServer/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fft-utils"
	@echo "... math"
	@echo "... misc-ident"
	@echo "... utils"
	@echo "... vol"
	@echo "... fast-clash"
	@echo "... fast-GB"
	@echo "... fast-hydro"
	@echo "... fast-LJ"
	@echo "... fast-PQ"
	@echo "... fast-resCont"
	@echo "... PG-range"
	@echo "... F2Dock"
	@echo "... GB-Rerank"
	@echo "... XmlRPC"
	@echo "... F2DockServer"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

